version: "3.9"

services:
  backend:
    build:
      context: ./agendamiento-autos
      dockerfile: Dockerfile
    container_name: honda-backend
    restart: always
    env_file:
      - .env.docker
    ports:
      - "4004:4004"

  frontend:
    build:
      context: ./agendamiento-autos-front
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: http://localhost:4004
    container_name: honda-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
